name: practicas
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_ui_auth: ^1.1.17
  flutterfire_cli: ^0.2.7
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.4.5
  firebase_core: ^2.16.0
  firebase_storage: ^11.0.16
  google_sign_in: ^5.4.4
  provider: ^6.0.5
  english_words: ^4.0.0
  cloud_functions: ^4.0.13
  firebase_database: ^10.0.16
  firebase_ui_oauth: ^1.4.0
  firebase_ui_oauth_google: ^1.0.21
  pay: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
   - assets/flutterfire_300x.png
   - assets/banner.jpg
   - assets/dash.png
   - assets/HiW.png
   - assets/erpia.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
