
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPesVKvD3Zx99T8uu6rDqN8WX8NZAWqHg',
    iosBundleId: 'com.example.helloWorld',
    appId: '1:888039703791:ios:ce598aeecb08634c1b471a',
    storageBucket: 'flutlab-flutter.appspot.com',
    messagingSenderId: '888039703791',
    iosClientId: '888039703791-pjlvr49dou7r4tko9l8uqlcq36b2hdoh.apps.googleusercontent.com',
    projectId: 'flutlab-flutter'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvZlbCCxphT-uVBQ3JYykLv5rgU3-zbE0',
    appId: '1:794742218118:android:439bb4c779a669be262007',
    messagingSenderId: '794742218118',
    projectId: 'flutterfire-ui-codelab-e4cbb',
    storageBucket: 'flutterfire-ui-codelab-e4cbb.appspot.com'
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJOo1bH4XsP7K4Jz76ZTK9Fi7MoYB8mHQ',
    authDomain: 'flutterfire-ui-codelab-e4cbb.firebaseapp.com',
    projectId: 'flutterfire-ui-codelab-e4cbb',
    storageBucket: 'flutterfire-ui-codelab-e4cbb-flutter.appspot.com',
    messagingSenderId: '794742218118',
    appId: '1:794742218118:web:8252e2c0e8594ddc262007'
  );
}
